image: docker:latest

stages:
- build
- release

services:
- docker:dind

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE_NAME: rpi-docker/couchdb
  CONTAINER_TEST_IMAGE: $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:test-$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
  - docker info
  - echo $CONTAINER_RELEASE_IMAGE

build:
  stage: build
  tags:
  - docker
  script:
  - docker build --pull -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE

deploy-to-registry:
  environment: GitLab
  stage: release
  tags:
  - docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master